In [1]:
# Part A: Conceptual Questions
print("=" * 60)
print("PART A: CONCEPTUAL QUESTIONS")
print("=" * 60)

print("""
1. Main differences between relational (SQL) and non-relational (NoSQL) databases:
   - Relational databases use structured tables with fixed schemas, support relationships 
     through keys, and use SQL for queries. NoSQL databases have flexible schemas, can 
     store unstructured data, and scale horizontally.
   - SQL example: Banking system where data integrity and complex transactions are critical
   - NoSQL example: Logging system with high-volume data and evolving structure

2. For an online bookstore, I recommend a relational database because:
   - Data has clear structure with multiple relationships (books-authors, orders-customers)
   - Data integrity is crucial for order processing
   - Complex queries are needed for sales analytics
   - ACID transactions are required for order management

3. ACID properties:
   - Atomicity: Transaction completes fully or not at all
   - Consistency: Data remains valid after transaction
   - Isolation: Concurrent transactions don't interfere
   - Durability: Committed changes persist
   Important for orders to prevent lost orders or double charges during failures

4. Primary key - unique identifier for each record (e.g., ISBN for books)
   Foreign key - references primary key in another table (e.g., customer_id in Orders table)

5. Data redundancy leads to:
   - Wasted storage space
   - Risk of data inconsistency
   - Difficult updates
   Normalization helps by organizing data into logical tables and eliminating duplication
""")

============================================================
PART A: CONCEPTUAL QUESTIONS
============================================================

1. Main differences between relational (SQL) and non-relational (NoSQL) databases:
   - Relational databases use structured tables with fixed schemas, support relationships
     through keys, and use SQL for queries. NoSQL databases have flexible schemas, can
     store unstructured data, and scale horizontally.
   - SQL example: Banking system where data integrity and complex transactions are critical
   - NoSQL example: Logging system with high-volume data and evolving structure

2. For an online bookstore, I recommend a relational database because:
   - Data has clear structure with multiple relationships (books-authors, orders-customers)
   - Data integrity is crucial for order processing
   - Complex queries are needed for sales analytics
   - ACID transactions are required for order management

3. ACID properties:
   - Atomicity: Transaction completes fully or not at all
   - Consistency: Data remains valid after transaction
   - Isolation: Concurrent transactions don't interfere
   - Durability: Committed changes persist
   Important for orders to prevent lost orders or double charges during failures

4. Primary key - unique identifier for each record (e.g., ISBN for books)
   Foreign key - references primary key in another table (e.g., customer_id in Orders table)

5. Data redundancy leads to:
   - Wasted storage space
   - Risk of data inconsistency
   - Difficult updates
   Normalization helps by organizing data into logical tables and eliminating duplication

In [10]:
# Part B: Database Schema
print("\n" + "=" * 60)
print("PART B: DATABASE SCHEMA")
print("=" * 60)

print("""
Relational Schema:

1. Authors
   - author_id INTEGER PRIMARY KEY
   - name VARCHAR(100) NOT NULL
   - birth_year INTEGER

2. Books
   - isbn VARCHAR(13) PRIMARY KEY
   - title VARCHAR(200) NOT NULL
   - publisher VARCHAR(100)
   - publication_year INTEGER
   - price DECIMAL(10,2) NOT NULL
   - stock_quantity INTEGER NOT NULL DEFAULT 0

3. BookAuthors (Junction Table)
   - book_isbn VARCHAR(13) FOREIGN KEY REFERENCES Books(isbn)
   - author_id INTEGER FOREIGN KEY REFERENCES Authors(author_id)
   - PRIMARY KEY (book_isbn, author_id)

4. Customers
   - customer_id INTEGER PRIMARY KEY
   - name VARCHAR(100) NOT NULL
   - email VARCHAR(100) UNIQUE NOT NULL
   - address TEXT
   - registration_date DATE NOT NULL

5. Orders
   - order_id INTEGER PRIMARY KEY
   - customer_id INTEGER FOREIGN KEY REFERENCES Customers(customer_id)
   - order_date DATE NOT NULL
   - total_amount DECIMAL(10,2)
   - status VARCHAR(20) CHECK (status IN ('pending', 'shipped', 'delivered', 'cancelled'))

6. OrderItems
   - order_item_id INTEGER PRIMARY KEY
   - order_id INTEGER FOREIGN KEY REFERENCES Orders(order_id)
   - book_isbn VARCHAR(13) FOREIGN KEY REFERENCES Books(isbn)
   - quantity INTEGER NOT NULL
   - price_at_time DECIMAL(10,2) NOT NULL
""")

============================================================
PART B: DATABASE SCHEMA
============================================================

Relational Schema:

1. Authors
   - author_id INTEGER PRIMARY KEY
   - name VARCHAR(100) NOT NULL
   - birth_year INTEGER

2. Books
   - isbn VARCHAR(13) PRIMARY KEY
   - title VARCHAR(200) NOT NULL
   - publisher VARCHAR(100)
   - publication_year INTEGER
   - price DECIMAL(10,2) NOT NULL
   - stock_quantity INTEGER NOT NULL DEFAULT 0

3. BookAuthors (Junction Table)
   - book_isbn VARCHAR(13) FOREIGN KEY REFERENCES Books(isbn)
   - author_id INTEGER FOREIGN KEY REFERENCES Authors(author_id)
   - PRIMARY KEY (book_isbn, author_id)

4. Customers
   - customer_id INTEGER PRIMARY KEY
   - name VARCHAR(100) NOT NULL
   - email VARCHAR(100) UNIQUE NOT NULL
   - address TEXT
   - registration_date DATE NOT NULL

5. Orders
   - order_id INTEGER PRIMARY KEY
   - customer_id INTEGER FOREIGN KEY REFERENCES Customers(customer_id)
   - order_date DATE NOT NULL
   - total_amount DECIMAL(10,2)
   - status VARCHAR(20) CHECK (status IN ('pending', 'shipped', 'delivered', 'cancelled'))

6. OrderItems
   - order_item_id INTEGER PRIMARY KEY
   - order_id INTEGER FOREIGN KEY REFERENCES Orders(order_id)
   - book_isbn VARCHAR(13) FOREIGN KEY REFERENCES Books(isbn)
   - quantity INTEGER NOT NULL
   - price_at_time DECIMAL(10,2) NOT NULL

In [ ]:
# Visual Data Explorer - Shows all tables with interactive widgets
print("=" * 60)
print("VISUAL DATA EXPLORER")
print("=" * 60)

from IPython.display import display, HTML

# Create a function to display table with nice formatting
def explore_table(table_name):
    df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
    
    print(f"\n{'='*60}")
    print(f"📊 {table_name.upper()}")
    print(f"{'='*60}")
    print(f"📈 Total Records: {len(df)}")
    print(f"📋 Columns: {', '.join(df.columns)}")
    
    # Display first 10 rows
    print(f"\n📄 First 10 rows:")
    display(df.head(10))
    
    # Display data types
    print(f"\n🔍 Data Types:")
    print(df.dtypes)
    
    # Display basic stats for numeric columns
    numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
    if len(numeric_cols) > 0:
        print(f"\n📊 Statistics for numeric columns:")
        display(df[numeric_cols].describe())
    
    return df

# Explore each table
for table in tables:
    table_name = table[0]
    explore_table(table_name)
    print("\n" + "="*60)

============================================================
VISUAL DATA EXPLORER
============================================================

============================================================
📊 AUTHORS
============================================================
📈 Total Records: 8
📋 Columns: author_id, name, birth_year

📄 First 10 rows:

   author_id                 name  birth_year
0          1        George Orwell        1903
1          2          Jane Austen        1775
2          3  F. Scott Fitzgerald        1896
3          4           Harper Lee        1926
4          5           Mark Twain        1835
5          6         J.K. Rowling        1965
6          7     Ernest Hemingway        1899
7          8          Leo Tolstoy        1828

🔍 Data Types:
author_id      int64
name          object
birth_year     int64
dtype: object

📊 Statistics for numeric columns:

       author_id   birth_year
count    8.00000     8.000000
mean     4.50000  1878.375000
std      2.44949    61.202095
min      1.00000  1775.000000
25%      2.75000  1833.250000
50%      4.50000  1897.500000
75%      6.25000  1908.750000
max      8.00000  1965.000000

============================================================

============================================================
📊 BOOKAUTHORS
============================================================
📈 Total Records: 10
📋 Columns: book_isbn, author_id

📄 First 10 rows:

       book_isbn  author_id
0  9780451524935          1
1  9780141439518          2
2  9780743273565          3
3  9780061120084          4
4  9780486280615          5
5  9780545582889          6
6  9780684801469          7
7  9781400079988          8
8  9780156012195          1
9  9780140283334          2

🔍 Data Types:
book_isbn    object
author_id     int64
dtype: object

📊 Statistics for numeric columns:

       author_id
count  10.000000
mean    3.900000
std     2.514403
min     1.000000
25%     2.000000
50%     3.500000
75%     5.750000
max     8.000000

============================================================

============================================================
📊 BOOKS
============================================================
📈 Total Records: 10
📋 Columns: isbn, title, publisher, publication_year, price, stock_quantity

📄 First 10 rows:

,isbn,title,publisher,publication_year,price,stock_quantity
0,9780451524935,1984,Signet Classics,1949,12.99,50
1,9780141439518,Pride and Prejudice,Penguin Classics,1813,9.99,35
2,9780743273565,The Great Gatsby,Scribner,1925,11.99,40
3,9780061120084,To Kill a Mockingbird,Harper Perennial,1960,14.99,25
4,9780486280615,The Adventures of Tom Sawyer,Dover Publications,1876,6.99,60
5,9780545582889,Harry Potter and the Sorcerer's Stone,Scholastic,1997,19.99,100
6,9780684801469,The Old Man and the Sea,Scribner,1952,10.99,30
7,9781400079988,War and Peace,Vintage,1869,18.99,20
8,9780156012195,Animal Farm,Harcourt,1945,8.99,45
9,9780140283334,Emma,Penguin Classics,1815,10.99,28

🔍 Data Types:
isbn                 object
title                object
publisher            object
publication_year      int64
price               float64
stock_quantity        int64
dtype: object

📊 Statistics for numeric columns:

       publication_year      price  stock_quantity
count         10.000000  10.000000       10.000000
mean        1910.100000  12.690000       43.300000
std           63.311312   4.191261       23.357369
min         1813.000000   6.990000       20.000000
25%         1870.750000  10.240000       28.500000
50%         1935.000000  11.490000       37.500000
75%         1951.250000  14.490000       48.750000
max         1997.000000  19.990000      100.000000

============================================================

============================================================
📊 CUSTOMERS
============================================================
📈 Total Records: 6
📋 Columns: customer_id, name, email, address, registration_date

📄 First 10 rows:

,customer_id,name,email,address,registration_date
0,1,John Smith,john.smith@email.com,"123 Main St, New York, NY",2023-01-15
1,2,Emma Johnson,emma.j@email.com,"456 Oak Ave, Los Angeles, CA",2023-03-20
2,3,Michael Brown,mike.brown@email.com,"789 Pine Rd, Chicago, IL",2023-06-10
3,4,Sarah Davis,sarah.davis@email.com,"321 Elm St, Houston, TX",2024-01-05
4,5,James Wilson,james.wilson@email.com,"654 Maple Dr, Phoenix, AZ",2024-02-18
5,6,Emily Taylor,emily.t@email.com,"987 Cedar Ln, Philadelphia, PA",2023-11-30

🔍 Data Types:
customer_id           int64
name                 object
email                object
address              object
registration_date    object
dtype: object

📊 Statistics for numeric columns:

       customer_id
count     6.000000
mean      3.500000
std       1.870829
min       1.000000
25%       2.250000
50%       3.500000
75%       4.750000
max       6.000000

============================================================

============================================================
📊 ORDERITEMS
============================================================
📈 Total Records: 14
📋 Columns: order_item_id, order_id, book_isbn, quantity, price_at_time

📄 First 10 rows:

   order_item_id  order_id      book_isbn  quantity  price_at_time
0              1         1  9780451524935         1          12.99
1              2         1  9780156012195         2           8.99
2              3         2  9780141439518         1           9.99
3              4         2  9780140283334         1          10.99
4              5         3  9780545582889         1          19.99
5              6         4  9780743273565         1          11.99
6              7         4  9780061120084         1          14.99
7              8         5  9780486280615         3           6.99
8              9         6  9780684801469         1          10.99
9             10         6  9781400079988         1          18.99

🔍 Data Types:
order_item_id      int64
order_id           int64
book_isbn         object
quantity           int64
price_at_time    float64
dtype: object

📊 Statistics for numeric columns:

       order_item_id   order_id   quantity  price_at_time
count        14.0000  14.000000  14.000000      14.000000
mean          7.5000   4.857143   1.285714      12.775714
std           4.1833   2.931451   0.611250       4.227721
min           1.0000   1.000000   1.000000       6.990000
25%           4.2500   2.250000   1.000000       9.990000
50%           7.5000   4.500000   1.000000      11.490000
75%          10.7500   6.750000   1.000000      14.490000
max          14.0000  10.000000   3.000000      19.990000

============================================================

============================================================
📊 ORDERS
============================================================
📈 Total Records: 10
📋 Columns: order_id, customer_id, order_date, total_amount, status

📄 First 10 rows:

   order_id  customer_id  order_date  total_amount     status
0         1            1  2024-01-10         30.97  delivered
1         2            2  2024-01-15         20.98  delivered
2         3            1  2024-02-01         19.99    shipped
3         4            3  2024-02-05         26.98    pending
4         5            4  2024-02-20         20.97    shipped
5         6            2  2024-03-01         29.98    pending
6         7            5  2024-03-05         12.99  delivered
7         8            6  2024-03-10         39.98    shipped
8         9            3  2023-12-15          9.99  delivered
9        10            4  2024-01-25          8.99  delivered

🔍 Data Types:
order_id          int64
customer_id       int64
order_date       object
total_amount    float64
status           object
dtype: object

📊 Statistics for numeric columns:

       order_id  customer_id  total_amount
count  10.00000     10.00000     10.000000
mean    5.50000      3.10000     22.182000
std     3.02765      1.66333      9.959432
min     1.00000      1.00000      8.990000
25%     3.25000      2.00000     14.740000
50%     5.50000      3.00000     20.975000
75%     7.75000      4.00000     29.230000
max    10.00000      6.00000     39.980000

============================================================

============================================================
📊 SQLITE_SEQUENCE
============================================================
📈 Total Records: 4
📋 Columns: name, seq

📄 First 10 rows:

         name  seq
0     Authors    8
1   Customers    6
2      Orders   10
3  OrderItems   14

🔍 Data Types:
name    object
seq      int64
dtype: object

📊 Statistics for numeric columns:

            seq
count   4.00000
mean    9.50000
std     3.41565
min     6.00000
25%     7.50000
50%     9.00000
75%    11.00000
max    14.00000

============================================================

:

In [ ]:
# Install: pip install matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

fig, ax = plt.subplots(1, 1, figsize=(20, 12))
ax.set_xlim(0, 20)
ax.set_ylim(0, 14)
ax.axis('off')

# Function to draw table boxes
def draw_table(x, y, title, columns, pk_cols=None, fk_cols=None):
    if pk_cols is None:
        pk_cols = []
    if fk_cols is None:
        fk_cols = []
    
    # Calculate box height
    box_height = 1.5 + len(columns) * 0.4
    box_width = 3.5
    
    # Draw box
    rect = FancyBboxPatch((x, y), box_width, box_height, 
                          boxstyle="round,pad=0.1", 
                          facecolor='lightblue', edgecolor='black', 
                          linewidth=2)
    ax.add_patch(rect)
    
    # Draw title
    ax.text(x + box_width/2, y + box_height - 0.25, title, 
            fontsize=12, fontweight='bold', ha='center')
    
    # Draw columns
    for i, col in enumerate(columns):
        y_pos = y + box_height - 0.7 - i * 0.4
        
        # Highlight PK and FK
        if col in pk_cols and col in fk_cols:
            col_text = f"🔑🔗 {col}"
            color = 'purple'
        elif col in pk_cols:
            col_text = f"🔑 {col}"
            color = 'red'
        elif col in fk_cols:
            col_text = f"🔗 {col}"
            color = 'blue'
        else:
            col_text = f"   {col}"
            color = 'black'
        
        ax.text(x + 0.2, y_pos, col_text, fontsize=9, color=color, 
                fontfamily='monospace')

# Draw all tables
draw_table(0, 8, "AUTHORS", 
           ['author_id', 'name', 'birth_year'], 
           pk_cols=['author_id'])

draw_table(5, 8, "BOOKAUTHORS", 
           ['book_isbn', 'author_id'], 
           pk_cols=['book_isbn', 'author_id'], 
           fk_cols=['book_isbn', 'author_id'])

draw_table(10, 8, "BOOKS", 
           ['isbn', 'title', 'publisher', 'publication_year', 'price', 'stock_quantity'], 
           pk_cols=['isbn'])

draw_table(0, 2, "CUSTOMERS", 
           ['customer_id', 'name', 'email', 'address', 'registration_date'], 
           pk_cols=['customer_id'])

draw_table(5, 2, "ORDERS", 
           ['order_id', 'customer_id', 'order_date', 'total_amount', 'status'], 
           pk_cols=['order_id'], 
           fk_cols=['customer_id'])

draw_table(10, 2, "ORDERITEMS", 
           ['order_item_id', 'order_id', 'book_isbn', 'quantity', 'price_at_time'], 
           pk_cols=['order_item_id'], 
           fk_cols=['order_id', 'book_isbn'])

# Draw relationships
def draw_arrow(x1, y1, x2, y2, label='', style='->'):
    arrow = FancyArrowPatch((x1, y1), (x2, y2), 
                            arrowstyle=style, 
                            color='gray', 
                            linewidth=1.5,
                            connectionstyle="arc3,rad=0.1")
    ax.add_patch(arrow)
    if label:
        mx = (x1 + x2) / 2
        my = (y1 + y2) / 2
        ax.text(mx, my, label, fontsize=8, color='gray', 
                bbox=dict(boxstyle="round,pad=0.2", facecolor='white', edgecolor='none'))

# Draw relationship lines
draw_arrow(3.5, 9.5, 5, 9.5, 'N')
draw_arrow(5, 9.5, 3.5, 9.5, '1')
draw_arrow(8.5, 9.5, 10, 9.5, 'N')
draw_arrow(10, 9.5, 8.5, 9.5, '1')
draw_arrow(3.5, 5.5, 5, 5.5, 'N')
draw_arrow(5, 5.5, 3.5, 5.5, '1')
draw_arrow(8.5, 5.5, 10, 5.5, 'N')
draw_arrow(10, 5.5, 8.5, 5.5, '1')

# Add legend
legend_x = 15
legend_y = 1
ax.text(legend_x, legend_y + 2.5, "LEGEND:", fontweight='bold', fontsize=11)
ax.text(legend_x, legend_y + 2.0, "🔑 Primary Key", fontsize=9, color='red')
ax.text(legend_x, legend_y + 1.6, "🔗 Foreign Key", fontsize=9, color='blue')
ax.text(legend_x, legend_y + 1.2, "🔑🔗 Composite PK/FK", fontsize=9, color='purple')
ax.text(legend_x, legend_y + 0.8, "1 : One", fontsize=9)
ax.text(legend_x, legend_y + 0.4, "N : Many", fontsize=9)
ax.text(legend_x, legend_y + 0.0, "→ Relationship", fontsize=9)

plt.title("ENTITY-RELATIONSHIP DIAGRAM\nOnline Bookstore Database", 
          fontsize=16, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('er_diagram_matplotlib.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ ER diagram saved as 'er_diagram_matplotlib.png'")

In [11]:
# Part C: SQL DDL - Creating Tables
print("\n" + "=" * 60)
print("PART C: CREATING TABLES (DDL)")
print("=" * 60)

import sqlite3
import pandas as pd
from datetime import datetime, timedelta

# Create database connection
conn = sqlite3.connect('bookstore.db')
cursor = conn.cursor()

# Drop existing tables
cursor.execute("DROP TABLE IF EXISTS OrderItems")
cursor.execute("DROP TABLE IF EXISTS Orders")
cursor.execute("DROP TABLE IF EXISTS Customers")
cursor.execute("DROP TABLE IF EXISTS BookAuthors")
cursor.execute("DROP TABLE IF EXISTS Books")
cursor.execute("DROP TABLE IF EXISTS Authors")

# Create Authors table
cursor.execute('''
CREATE TABLE Authors (
    author_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    birth_year INTEGER
)
''')

# Create Books table
cursor.execute('''
CREATE TABLE Books (
    isbn VARCHAR(13) PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    publisher VARCHAR(100),
    publication_year INTEGER,
    price DECIMAL(10,2) NOT NULL,
    stock_quantity INTEGER NOT NULL DEFAULT 0
)
''')

# Create BookAuthors junction table
cursor.execute('''
CREATE TABLE BookAuthors (
    book_isbn VARCHAR(13),
    author_id INTEGER,
    PRIMARY KEY (book_isbn, author_id),
    FOREIGN KEY (book_isbn) REFERENCES Books(isbn) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (author_id) REFERENCES Authors(author_id) ON DELETE CASCADE ON UPDATE CASCADE
)
''')

# Create Customers table
cursor.execute('''
CREATE TABLE Customers (
    customer_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    address TEXT,
    registration_date DATE NOT NULL
)
''')

# Create Orders table
cursor.execute('''
CREATE TABLE Orders (
    order_id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER NOT NULL,
    order_date DATE NOT NULL,
    total_amount DECIMAL(10,2),
    status VARCHAR(20) CHECK (status IN ('pending', 'shipped', 'delivered', 'cancelled')),
    FOREIGN KEY (customer_id) REFERENCES Customers(customer_id) ON DELETE RESTRICT ON UPDATE CASCADE
)
''')

# Create OrderItems table
cursor.execute('''
CREATE TABLE OrderItems (
    order_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL,
    book_isbn VARCHAR(13) NOT NULL,
    quantity INTEGER NOT NULL,
    price_at_time DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES Orders(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (book_isbn) REFERENCES Books(isbn) ON DELETE RESTRICT ON UPDATE CASCADE
)
''')

print("✓ Tables created successfully")
conn.commit()

============================================================
PART C: CREATING TABLES (DDL)
============================================================
✓ Tables created successfully

In [12]:
print("\n1. LIST ALL TABLES:")
print("-" * 40)

# Get all table names from sqlite_master
cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;")
tables = cursor.fetchall()
print("Tables in database:")
for table in tables:
    print(f"  - {table[0]}")

1. LIST ALL TABLES:
----------------------------------------
Tables in database:
  - Authors
  - BookAuthors
  - Books
  - Customers
  - OrderItems
  - Orders
  - sqlite_sequence

In [13]:
# Part D: Populating the Database
print("\n" + "=" * 60)
print("PART D: POPULATING DATABASE")
print("=" * 60)

# Insert Authors
authors_data = [
    ('George Orwell', 1903),
    ('Jane Austen', 1775),
    ('F. Scott Fitzgerald', 1896),
    ('Harper Lee', 1926),
    ('Mark Twain', 1835),
    ('J.K. Rowling', 1965),
    ('Ernest Hemingway', 1899),
    ('Leo Tolstoy', 1828)
]

cursor.executemany('INSERT INTO Authors (name, birth_year) VALUES (?, ?)', authors_data)
print(f"✓ Added {len(authors_data)} authors")

# Insert Books
books_data = [
    ('9780451524935', '1984', 'Signet Classics', 1949, 12.99, 50),
    ('9780141439518', 'Pride and Prejudice', 'Penguin Classics', 1813, 9.99, 35),
    ('9780743273565', 'The Great Gatsby', 'Scribner', 1925, 11.99, 40),
    ('9780061120084', 'To Kill a Mockingbird', 'Harper Perennial', 1960, 14.99, 25),
    ('9780486280615', 'The Adventures of Tom Sawyer', 'Dover Publications', 1876, 6.99, 60),
    ('9780545582889', "Harry Potter and the Sorcerer's Stone", 'Scholastic', 1997, 19.99, 100),
    ('9780684801469', 'The Old Man and the Sea', 'Scribner', 1952, 10.99, 30),
    ('9781400079988', 'War and Peace', 'Vintage', 1869, 18.99, 20),
    ('9780156012195', 'Animal Farm', 'Harcourt', 1945, 8.99, 45),
    ('9780140283334', 'Emma', 'Penguin Classics', 1815, 10.99, 28)
]

cursor.executemany('INSERT INTO Books (isbn, title, publisher, publication_year, price, stock_quantity) VALUES (?, ?, ?, ?, ?, ?)', books_data)
print(f"✓ Added {len(books_data)} books")

# Link Books with Authors
book_authors_data = [
    ('9780451524935', 1),  # 1984 - Orwell
    ('9780141439518', 2),  # Pride and Prejudice - Austen
    ('9780743273565', 3),  # Great Gatsby - Fitzgerald
    ('9780061120084', 4),  # To Kill a Mockingbird - Lee
    ('9780486280615', 5),  # Tom Sawyer - Twain
    ('9780545582889', 6),  # Harry Potter - Rowling
    ('9780684801469', 7),  # Old Man and Sea - Hemingway
    ('9781400079988', 8),  # War and Peace - Tolstoy
    ('9780156012195', 1),  # Animal Farm - Orwell (second author)
    ('9780140283334', 2),  # Emma - Austen (second author)
]

cursor.executemany('INSERT INTO BookAuthors (book_isbn, author_id) VALUES (?, ?)', book_authors_data)
print(f"✓ Added {len(book_authors_data)} book-author relationships")

# Insert Customers
customers_data = [
    ('John Smith', 'john.smith@email.com', '123 Main St, New York, NY', '2023-01-15'),
    ('Emma Johnson', 'emma.j@email.com', '456 Oak Ave, Los Angeles, CA', '2023-03-20'),
    ('Michael Brown', 'mike.brown@email.com', '789 Pine Rd, Chicago, IL', '2023-06-10'),
    ('Sarah Davis', 'sarah.davis@email.com', '321 Elm St, Houston, TX', '2024-01-05'),
    ('James Wilson', 'james.wilson@email.com', '654 Maple Dr, Phoenix, AZ', '2024-02-18'),
    ('Emily Taylor', 'emily.t@email.com', '987 Cedar Ln, Philadelphia, PA', '2023-11-30')
]

cursor.executemany('INSERT INTO Customers (name, email, address, registration_date) VALUES (?, ?, ?, ?)', customers_data)
print(f"✓ Added {len(customers_data)} customers")

# Insert Orders
orders_data = [
    (1, '2024-01-10', None, 'delivered'),
    (2, '2024-01-15', None, 'delivered'),
    (1, '2024-02-01', None, 'shipped'),
    (3, '2024-02-05', None, 'pending'),
    (4, '2024-02-20', None, 'shipped'),
    (2, '2024-03-01', None, 'pending'),
    (5, '2024-03-05', None, 'delivered'),
    (6, '2024-03-10', None, 'shipped'),
    (3, '2023-12-15', None, 'delivered'),
    (4, '2024-01-25', None, 'delivered')
]

cursor.executemany('INSERT INTO Orders (customer_id, order_date, total_amount, status) VALUES (?, ?, ?, ?)', orders_data)
print(f"✓ Added {len(orders_data)} orders")

# Insert Order Items
order_items_data = [
    (1, '9780451524935', 1, 12.99),  # Order 1: 1984
    (1, '9780156012195', 2, 8.99),   # Order 1: Animal Farm
    (2, '9780141439518', 1, 9.99),   # Order 2: Pride and Prejudice
    (2, '9780140283334', 1, 10.99),  # Order 2: Emma
    (3, '9780545582889', 1, 19.99),  # Order 3: Harry Potter
    (4, '9780743273565', 1, 11.99),  # Order 4: Great Gatsby
    (4, '9780061120084', 1, 14.99),  # Order 4: To Kill a Mockingbird
    (5, '9780486280615', 3, 6.99),   # Order 5: Tom Sawyer (3 copies)
    (6, '9780684801469', 1, 10.99),  # Order 6: Old Man and Sea
    (6, '9781400079988', 1, 18.99),  # Order 6: War and Peace
    (7, '9780451524935', 1, 12.99),  # Order 7: 1984
    (8, '9780545582889', 2, 19.99),  # Order 8: Harry Potter (2 copies)
    (9, '9780141439518', 1, 9.99),   # Order 9: Pride and Prejudice
    (10, '9780156012195', 1, 8.99),  # Order 10: Animal Farm
]

cursor.executemany('INSERT INTO OrderItems (order_id, book_isbn, quantity, price_at_time) VALUES (?, ?, ?, ?)', order_items_data)
print(f"✓ Added {len(order_items_data)} order items")

# Update order totals
cursor.execute('''
UPDATE Orders 
SET total_amount = (
    SELECT SUM(quantity * price_at_time)
    FROM OrderItems
    WHERE OrderItems.order_id = Orders.order_id
)
''')
print("✓ Updated order totals")

conn.commit()
print("\n✓ Database successfully populated!")

============================================================
PART D: POPULATING DATABASE
============================================================
✓ Added 8 authors
✓ Added 10 books
✓ Added 10 book-author relationships
✓ Added 6 customers
✓ Added 10 orders
✓ Added 14 order items
✓ Updated order totals

✓ Database successfully populated!

In [6]:
# Part E: SQL Queries
print("\n" + "=" * 60)
print("PART E: SQL QUERIES")
print("=" * 60)

# Query 1: List all books with their title, author(s), and price
print("\n" + "-" * 40)
print("1. All books with authors and price:")
print("-" * 40)

query1 = '''
SELECT b.title, GROUP_CONCAT(a.name, ', ') as authors, b.price
FROM Books b
JOIN BookAuthors ba ON b.isbn = ba.book_isbn
JOIN Authors a ON ba.author_id = a.author_id
GROUP BY b.isbn, b.title, b.price
ORDER BY b.title
'''
df1 = pd.read_sql_query(query1, conn)
print(df1.to_string(index=False))

# Query 2: Find all customers who registered in 2023
print("\n" + "-" * 40)
print("2. Customers registered in 2023:")
print("-" * 40)

query2 = '''
SELECT name, email, registration_date
FROM Customers
WHERE strftime('%Y', registration_date) = '2023'
'''
df2 = pd.read_sql_query(query2, conn)
print(df2.to_string(index=False))

# Query 3: Show pending orders from the last 30 days
print("\n" + "-" * 40)
print("3. Pending orders from the last 30 days (from 2024-03-20):")
print("-" * 40)

query3 = '''
SELECT o.order_id, c.name, o.order_date, o.total_amount, o.status
FROM Orders o
JOIN Customers c ON o.customer_id = c.customer_id
WHERE o.status = 'pending' 
  AND o.order_date >= date('2024-03-20', '-30 days')
ORDER BY o.order_date DESC
'''
df3 = pd.read_sql_query(query3, conn)
print(df3.to_string(index=False) if not df3.empty else "No pending orders in the last 30 days")

# Query 4: Count how many books each author has written
print("\n" + "-" * 40)
print("4. Number of books written by each author:")
print("-" * 40)

query4 = '''
SELECT a.name, COUNT(ba.book_isbn) as books_count
FROM Authors a
LEFT JOIN BookAuthors ba ON a.author_id = ba.author_id
GROUP BY a.author_id, a.name
ORDER BY books_count DESC
'''
df4 = pd.read_sql_query(query4, conn)
print(df4.to_string(index=False))

# Query 5: Total number of orders placed by each customer
print("\n" + "-" * 40)
print("5. Total orders by customer (sorted descending):")
print("-" * 40)

query5 = '''
SELECT c.name, COUNT(o.order_id) as order_count
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
ORDER BY order_count DESC
'''
df5 = pd.read_sql_query(query5, conn)
print(df5.to_string(index=False))

# Query 6: Calculate total revenue from all orders
print("\n" + "-" * 40)
print("6. Total revenue from all orders:")
print("-" * 40)

query6 = '''
SELECT SUM(quantity * price_at_time) as total_revenue
FROM OrderItems
'''
df6 = pd.read_sql_query(query6, conn)
print(f"Total Revenue: ${df6['total_revenue'].iloc[0]:.2f}")

# Query 7: Find top 3 best-selling books by quantity sold
print("\n" + "-" * 40)
print("7. Top 3 best-selling books:")
print("-" * 40)

query7 = '''
SELECT b.title, SUM(oi.quantity) as total_sold
FROM Books b
JOIN OrderItems oi ON b.isbn = oi.book_isbn
GROUP BY b.isbn, b.title
ORDER BY total_sold DESC
LIMIT 3
'''
df7 = pd.read_sql_query(query7, conn)
print(df7.to_string(index=False))

# Query 8: List customers who spent more than $100
print("\n" + "-" * 40)
print("8. Customers who spent more than $100:")
print("-" * 40)

query8 = '''
SELECT c.name, SUM(oi.quantity * oi.price_at_time) as total_spent
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN OrderItems oi ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.name
HAVING total_spent > 100
ORDER BY total_spent DESC
'''
df8 = pd.read_sql_query(query8, conn)
print(df8.to_string(index=False) if not df8.empty else "No customers spent more than $100")

# Query 9: Monthly orders and sales for 2024
print("\n" + "-" * 40)
print("9. Monthly orders and sales for 2024:")
print("-" * 40)

query9 = '''
SELECT 
    strftime('%Y-%m', order_date) as month,
    COUNT(order_id) as order_count,
    SUM(total_amount) as total_sales
FROM Orders
WHERE strftime('%Y', order_date) = '2024'
GROUP BY strftime('%Y-%m', order_date)
ORDER BY month
'''
df9 = pd.read_sql_query(query9, conn)
print(df9.to_string(index=False))

============================================================
PART E: SQL QUERIES
============================================================

----------------------------------------
1. All books with authors and price:
----------------------------------------
                                title             authors  price
                                 1984       George Orwell  12.99
                          Animal Farm       George Orwell   8.99
                                 Emma         Jane Austen  10.99
Harry Potter and the Sorcerer's Stone        J.K. Rowling  19.99
                  Pride and Prejudice         Jane Austen   9.99
         The Adventures of Tom Sawyer          Mark Twain   6.99
                     The Great Gatsby F. Scott Fitzgerald  11.99
              The Old Man and the Sea    Ernest Hemingway  10.99
                To Kill a Mockingbird          Harper Lee  14.99
                        War and Peace         Leo Tolstoy  18.99

----------------------------------------
2. Customers registered in 2023:
----------------------------------------
         name                email registration_date
   John Smith john.smith@email.com        2023-01-15
 Emma Johnson     emma.j@email.com        2023-03-20
Michael Brown mike.brown@email.com        2023-06-10
 Emily Taylor    emily.t@email.com        2023-11-30

----------------------------------------
3. Pending orders from the last 30 days (from 2024-03-20):
----------------------------------------
 order_id         name order_date  total_amount  status
        6 Emma Johnson 2024-03-01         29.98 pending

----------------------------------------
4. Number of books written by each author:
----------------------------------------
               name  books_count
      George Orwell            2
        Jane Austen            2
F. Scott Fitzgerald            1
         Harper Lee            1
         Mark Twain            1
       J.K. Rowling            1
   Ernest Hemingway            1
        Leo Tolstoy            1

----------------------------------------
5. Total orders by customer (sorted descending):
----------------------------------------
         name  order_count
   John Smith            2
 Emma Johnson            2
Michael Brown            2
  Sarah Davis            2
 James Wilson            1
 Emily Taylor            1

----------------------------------------
6. Total revenue from all orders:
----------------------------------------
Total Revenue: $221.82

----------------------------------------
7. Top 3 best-selling books:
----------------------------------------
                                title  total_sold
                          Animal Farm           3
         The Adventures of Tom Sawyer           3
Harry Potter and the Sorcerer's Stone           3

----------------------------------------
8. Customers who spent more than $100:
----------------------------------------
No customers spent more than $100

----------------------------------------
9. Monthly orders and sales for 2024:
----------------------------------------
  month  order_count  total_sales
2024-01            3        60.94
2024-02            3        67.94
2024-03            3        82.95

In [7]:
# Additional Queries for Verification
print("\n" + "-" * 40)
print("ADDITIONAL ANALYSIS:")
print("-" * 40)

# Books with multiple authors
query_multiple = '''
SELECT b.title, COUNT(ba.author_id) as author_count
FROM Books b
JOIN BookAuthors ba ON b.isbn = ba.book_isbn
GROUP BY b.isbn, b.title
HAVING author_count > 1
'''
df_multiple = pd.read_sql_query(query_multiple, conn)
print("\nBooks with multiple authors:")
print(df_multiple.to_string(index=False))

# Order status statistics
query_status = '''
SELECT status, COUNT(*) as count, SUM(total_amount) as total
FROM Orders
GROUP BY status
'''
df_status = pd.read_sql_query(query_status, conn)
print("\nOrder status statistics:")
print(df_status.to_string(index=False))

# Inventory status
query_inventory = '''
SELECT title, stock_quantity, price
FROM Books
ORDER BY stock_quantity DESC
'''
df_inventory = pd.read_sql_query(query_inventory, conn)
print("\nCurrent inventory status:")
print(df_inventory.to_string(index=False))

----------------------------------------
ADDITIONAL ANALYSIS:
----------------------------------------

Books with multiple authors:
Empty DataFrame
Columns: [title, author_count]
Index: []

Order status statistics:
   status  count  total
delivered      5  83.92
  pending      2  56.96
  shipped      3  80.94

Current inventory status:
                                title  stock_quantity  price
Harry Potter and the Sorcerer's Stone             100  19.99
         The Adventures of Tom Sawyer              60   6.99
                                 1984              50  12.99
                          Animal Farm              45   8.99
                     The Great Gatsby              40  11.99
                  Pride and Prejudice              35   9.99
              The Old Man and the Sea              30  10.99
                                 Emma              28  10.99
                To Kill a Mockingbird              25  14.99
                        War and Peace              20  18.99

In [8]:
# Close database connection
print("\n" + "=" * 60)
print("LAB COMPLETED SUCCESSFULLY")
print("=" * 60)

conn.close()
print("\nDatabase connection closed.")

============================================================
LAB COMPLETED SUCCESSFULLY
============================================================

Database connection closed.

In [9]:
# Visual Data Explorer - Shows all tables with interactive widgets
print("=" * 60)
print("VISUAL DATA EXPLORER")
print("=" * 60)

from IPython.display import display, HTML

# Create a function to display table with nice formatting
def explore_table(table_name):
    df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
    
    print(f"\n{'='*60}")
    print(f"📊 {table_name.upper()}")
    print(f"{'='*60}")
    print(f"📈 Total Records: {len(df)}")
    print(f"📋 Columns: {', '.join(df.columns)}")
    
    # Display first 10 rows
    print(f"\n📄 First 10 rows:")
    display(df.head(10))
    
    # Display data types
    print(f"\n🔍 Data Types:")
    print(df.dtypes)
    
    # Display basic stats for numeric columns
    numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
    if len(numeric_cols) > 0:
        print(f"\n📊 Statistics for numeric columns:")
        display(df[numeric_cols].describe())
    
    return df

# Explore each table
for table in tables:
    table_name = table[0]
    explore_table(table_name)
    print("\n" + "="*60)

============================================================
VISUAL DATA EXPLORER
============================================================

ProgrammingError: Cannot operate on a closed database.